### PR TITLE
offchain worker bugs

### LINKED ISSUE #23: Offchain workers - bug
Currently after each session finalisation, there is an extra pending extrinsic. This number grows over the time to infinite number.

Similar thing with NFT offchain worker, even when condition is not fired - there is a call for unsigned_transaction every block...

### Requirements
- Check if there is no logic error when sending signed payload
- Maybe implementing a lock at the beginning of offchain worker would solve the problem?

### PR DESCRIPTION
**Pull request by korzewski**
Resolves #23

### CODE REVIEW

File: pallets/jackblock/src/lib.rs [hunk 1]
```diff
@@ -557,30 +568,27 @@ impl<T: Config> ValidateUnsigned for Module<T> {
...
-				}
-
 				// TODO - use aura keys to check authority
 
 				let account_id = payload.public.clone().into_account();
 				if !Self::is_authority_account(&account_id) {
 					return InvalidTransaction::BadProof.into();
 				}
+				
+				let valid_signature = SignedPayload::<T>::verify::<T::AuthorityId>(payload, signature.clone());
```
Comment (korzewski) [inline pallets/jackblock/src/lib.rs:578]: Based on conversation with Tomek Drwięga, checks should be ordered from lightest to largest. Only order is changed here

File: pallets/jackblock/src/lib.rs [hunk 2]
```diff
@@ -589,8 +597,15 @@ impl<T: Config> ValidateUnsigned for Module<T> {
 					return InvalidTransaction::BadProof.into();
 				}
```
Comment (korzewski) [inline pallets/jackblock/src/lib.rs:599]: same here, only order has changed

**Review by deployAt — APPROVED** [review]
🚀 🚀 🚀
